# Generated by Django 5.2 on 2025-04-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_rename_options_question_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='questionlistening',
            name='title',
        ),
    ]
