# Generated by Django 5.2 on 2025-04-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_remove_question_title_remove_questionlistening_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='questionlistening',
            name='preview',
        ),
    ]
