# Generated by Django 5.2 on 2025-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_remove_question_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('grammar', 'Grammar')], default='vocabulary'),
        ),
    ]
