# Generated by Django 5.2 on 2025-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_section_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('grammar', 'Grammar')], default='vocabulary', max_length=20),
        ),
    ]
