# Generated by Django 4.2.6 on 2025-04-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_alter_section_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionGrammar',
        ),
        migrations.CreateModel(
            name='QuestionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
                ('correct', models.CharField(max_length=255)),
                ('errorText', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reading', to='app_backend.section')),
            ],
        ),
    ]
