# Generated by Django 5.2 on 2025-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='public_test',
            field=models.BooleanField(default=True),
        ),
    ]
