# Generated by Django 5.2 on 2025-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_section_public_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongrammar',
            name='number_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionlistening',
            name='number_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionreading',
            name='number_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vocabularydata',
            name='number_points',
            field=models.IntegerField(default=1),
        ),
    ]
