# Generated by Django 4.2.6 on 2025-04-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_questiongrammar_number_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('present', 'Present'), ('past', 'Past'), ('future', 'Future')], default='present', max_length=8)),
            ],
        ),
    ]
