# Generated by Django 4.2.6 on 2025-04-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0012_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('formula', models.TextField()),
                ('examples', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PastTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('formula', models.TextField()),
                ('examples', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('formula', models.TextField()),
                ('examples', models.TextField()),
            ],
        ),
    ]
