# Generated by Django 5.2 on 2025-05-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0014_futuretime_image_pasttime_image_presenttime_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Times',
        ),
    ]
